-- این فایل را یک بار در Supabase > SQL Editor اجرا کنید.
-- جدول اصلی کتاب‌ها + داده‌های اولیه + تابع اتمیک جابه‌جایی ترتیب

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 160),
  category text not null check (category in ('public', 'basij')),
  position integer not null,
  is_deleted boolean not null default false,
  deleted_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists books_position_idx on public.books(position);
create index if not exists books_active_idx on public.books(is_deleted, position);

alter table public.books enable row level security;

-- هیچ دسترسی مستقیم عمومی تعریف نشده است؛ برنامه از API سرور و Secret Key استفاده می‌کند.
revoke all on table public.books from anon, authenticated;
grant all on table public.books to service_role;

do $$
begin
  if not exists (select 1 from public.books) then
    insert into public.books (title, category, position) values
      ('پنج طلوع بی غروب', 'public', 1),
      ('سرباز ولايت', 'public', 2),
      ('شکارچی', 'public', 3),
      ('يه يادگاري از شهيد', 'public', 4),
      ('بانوي شهيده', 'public', 5),
      ('آتش عشق', 'public', 6),
      ('قرار هشتم', 'public', 7),
      ('دلاور دریا', 'public', 8),
      ('حماسه تیربار', 'public', 9),
      ('جانم فدای خاک وطنم', 'public', 10),
      ('ماه پنهان', 'public', 11),
      ('ميثاق قدس', 'public', 12),
      ('عهد سرخ', 'public', 13),
      ('پابوس شه طوس', 'basij', 14),
      ('ماموریت وصال', 'basij', 15),
      ('مروارید عمان', 'basij', 16),
      ('چشم بیدار', 'basij', 17),
      ('رجعت سرباز', 'basij', 18),
      ('یکه تاز', 'basij', 19),
      ('بر مدار وفا', 'basij', 20),
      ('طلوع حسین وار', 'basij', 21),
      ('فاتح گمنام', 'basij', 22),
      ('قربان رضا', 'basij', 23),
      ('دلداده حرم', 'public', 24);
  end if;
end $$;

create or replace function public.reorder_books(ordered_ids bigint[])
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.books as b
  set position = x.ord::integer,
      updated_at = now()
  from unnest(ordered_ids) with ordinality as x(id, ord)
  where b.id = x.id
    and b.is_deleted = false;
end;
$$;

revoke all on function public.reorder_books(bigint[]) from public, anon, authenticated;
grant execute on function public.reorder_books(bigint[]) to service_role;
